version: '3.9'

services:
  djangoapp:
    # user: duser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    image: postgres:13-alpine3.18
    volumes:
      - ./data/postgres/data:/var/lib/postgres/data/
    env_file:
      - ./dotenv_files/.env
